[project]
name = "statisticallearning"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "islp>=0.4.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
]
